---
version: "3.8"

services:
  bitwarden:
    depends_on:
      - db
    env_file:
      - /opt/docker/bitwarden/settings.env
    image: ${REGISTRY:-bitwarden}/self-host:${TAG:-beta}
    restart: always
    ports:
      - "<bitwarden-port>:8080"

  db:
    environment:
      MARIADB_USER: "bitwarden"
      MARIADB_PASSWORD: "<db-password>"
      MARIADB_DATABASE: "bitwarden_vault"
      MARIADB_RANDOM_ROOT_PASSWORD: "true"
    image: mariadb:10
    restart: always
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
