---
version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed

services:
  nextcloud:
    image: nextcloud/all-in-one:latest-arm64 #for ARM, like RasperryPi or Oracle Cloud A1
    #image: nextcloud/all-in-one:latest #for x86_64
    restart: always
    container_name: nextcloud-aio-mastercontainer     
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'DOCKER_SOCKET_PATH'!
    ports:
      - 81:80
      - 8080:8080
      - 8443:8443
    environment:
      - APACHE_PORT=<nextcloud-port>
